### ISSUE TITLE
[REQUEST] Optional parameter in url?

### ISSUE THREAD

**Issue by didix16** [nodefony/nodefony#18]
Hi guys. I'm using this amazing beta framework :) and I'm just wondering if it's implemented the optional url parameter. I'm just trying to make it as symfony does but I'm getting Not found HTTP 404.

So it's still unavaiable or.. maybe I'm doing something wrong? I just put the variable in "defaults" parameter with a default value.

Thanks in advance.

**Comment by ccamensuli** [comment]
You do nothing wrong , Optional url parameter is not implemented !! 

 open an issue for new  enhancement.

Warning !! 
Nodefony will soon migrate in with branch ES6 in the next beta release  .
The way to code change to full ECMAScript Edition 6 (ES6) ( Class and Inheritance ) 


Thank you for the attention to this framework.

**Comment by didix16** [comment]
Hold on dude, you are doing so good, the framework looks pretty nice :D.

**Comment by ccamensuli** [comment]
I didix16 

You can now use Optional parameter in url in Nodefony v2.0.2-beta.

```yaml
my-route:
  pattern:      /myroute/{page}/{elements}
  defaults:     {"controller": "demoBundle:test:myroute","page":13,"elements":"foo"}
  requirements:
    method:     GET
    page:       "^\\d\\d$"
```
